export const getIconName = (name: string | null): any => {
  const map: Record<string, string> = {
    // default
    'vacuum': 'robot-vacuum',
    'shower': 'shower',
    'toilet': 'toilet',
    'chef-hat': 'chef-hat',
    'droplets': 'water',
    'feather': 'feather',
    'shirt': 'tshirt-crew',
    'utensils': 'silverware',
    'trash-2': 'trash-can-outline',
    'flower-2': 'flower-outline',
    'layout': 'view-dashboard-outline',
    'thermometer': 'thermometer',
    'car': 'car-outline',
    'package': 'package-variant-closed',
    'shovel': 'shovel',
    'calendar': 'calendar-outline',
    'check': 'check',
    'star': 'star',
    
    // new custom options
    'home': 'home-outline',
    'heart': 'heart-outline',
    'wrench': 'wrench',
    'scissors': 'wrench-outline',
    'dog': 'dog',
    'cat': 'cat',
    'sprout': 'sprout',
    'cart': 'cart-outline',
    'bike': 'car-hatchback',
    'book': 'book-open-outline',
    'laptop': 'laptop',
    'monitor': 'monitor',
    'hammer': 'hammer-wrench',
    'pill': 'pill',
    'medical': 'medical-bag',
    'baby': 'baby-carriage',
    'run': 'run',
    'music': 'music-note',
    'camera': 'camera-outline',
    'bed': 'bed-empty',
    'tshirt': 'tshirt-v',
    'sofa': 'sofa-outline',
    'hanger': 'hanger',
    'iron': 'iron-outline',
    'washing-machine': 'washing-machine',
    'broom': 'broom',
    'mop': 'mop',
  };
  return map[name || 'check'] || name || 'check';
};
